server:
  port: 8081
#Config MYSQL
spring:
  application:
    name: app-be-appointment-management
  config:
    import: optional:file:.env
#  main:
#    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:mysql://localhost:3308/${DATABASE_NAME}?createDatabaseIfNotExist=true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      #dd-auto: none
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: TRACE

  pattern:
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){bright_green}
      %clr(%5p){INFO=green, WARN=yellow, ERROR=red}
      %clr(${PID:- }){magenta}
      %clr(---){faint}
      %clr([%15.15t]){blue}
      %clr(%-40.40logger{39}){cyan}
      %clr(:){faint}
      %clr(%m){WARN=yellow, ERROR=bright_red}%n%clr(%wEx){bright_red}

    exception-conversion-word: "%clr(%rootException){bright_red}"
